GET http://localhost:5275/genres

###

GET http://localhost:5275/genres/1

###

POST http://localhost:5275/genres
Content-Type: application/json

{
    "name": "Deneme"
}

###

PUT http://localhost:5275/genres/8
Content-Type: application/json

{
  "name": "Deneme2",
  "Id": 6
}

###

DELETE http://localhost:5275/genres/7